version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tuto-app
    restart: always
    working_dir: /home/rusty/www/
    volumes:
      - ../:/home/rusty/www
  nginx:
    image: nginx:1.19-alpine
    container_name: tuto-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/home/rusty/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: tuto-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
